# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  platform-orb: okta/general-platform-helpers@1.2.2

jobs:
  cache-secrets:
    machine: true
    resource_class: okta/generic-linux-x86
    environment:
      VAULT_ADDR: https://vault.aue1e.saasure.net
    steps:
      - checkout
      - run: echo $vault_username
      - run:
          name: "Vault login"
          command: |
            vault login -method=userpass username=$vault_username password=$vault_password > /dev/null 2>&1
      - platform-orb/save-dependencies

  test:
    docker:
    - image: cimg/go:1.19.4
    steps:
    - checkout
    - run: sudo apt-get update
    - run: sudo apt-get install -y software-properties-common npm
    - run: npm install axios --save
    - run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
    - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - run: sudo apt-get update
    - run: sudo apt-get install google-chrome-stable
    - platform-orb/load-dependencies
    - run: npm test

workflows:
  "Circle CI Tests":
    jobs:
      - cache-secrets
      # - test:
      #     requires:
      #       - cache-secrets